name: Build release APK

on:
  workflow_dispatch:
  push:
    branches:
      - 12.1-dev

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Stop gradle daemon
        run: ls -lR
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: build/outputs
          TELEGRAM_CI_CHANNEL_ID: ${{ secrets.TELEGRAM_CI_CHANNEL_ID }}
          TELEGRAM_TEAM_GROUP_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
          ARTIFACT_DIRECTORY: artifacts/release-apk
          GITHUB_REF: ${{ github.ref }}
}
          TELEGRAM_TEAM_GROUP_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
          ARTIFACT_DIRECTORY: artifacts/release-apk
          GITHUB_REF: ${{ github.ref }}TELEGRAM_CI_CHANNEL_ID }}
          TELEGRAM_TEAM_GROUP_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
          ARTIFACT_DIRECTORY: artifacts/release-apk
          GITHUB_REF: ${{ github.ref }}
